version: "3.9"
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - redis

volumes:
  redis-data:
