version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
