version: "3.9"
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    hostname: redis
    volumes:
      - redis-data:/data
  api:
    restart: on-failure
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redis

volumes:
  redis-data:
